server:
  port: ${SERVICE_PORT:8083}
spring:
  application:
    name: carson-cloud-business
  profiles:
    active: ${SPRING_PROFILE:dev}
  jackson:
    serialization:
      write-dates-as-timestamps: true
logging:
  file:
    name: ${logging.file.path}/application.log
    path: /log/${spring.application.name}
  level:
    root: info